import {
  Card,
  CardContent,
  CardFooter,
} from "@/apps/nextjs-app/components/ui/card";

interface InfoCardProps {
  type: "issue" | "recommendation";
  title: string;
  content: string;
  source: string;
  onEdit?: () => void;
  onDelete?: () => void;
}

export function InfoCard({
  type,
  title,
  content,
  source,
  onEdit,
  onDelete,
}: InfoCardProps) {
  return (
    <Card className="group relative bg-indigo-100">
      <div className="absolute right-4 top-4 flex items-center gap-2 opacity-0 transition-opacity group-hover:opacity-100">
        <button
          onClick={onEdit}
          className="text-gray-600 transition-colors hover:text-gray-900"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            height="16"
            viewBox="0 -960 960 960"
            width="16"
            fill="currentColor"
          >
            <path d="M200-200h57l391-391-57-57-391 391v57Zm-80 80v-170l528-527q12-11 26.5-17t30.5-6q16 0 31 6t26 18l55 56q12 11 17.5 26t5.5 30q0 16-5.5 30.5T817-647L290-120H120Zm640-584-56-56 56 56Zm-141 85-28-29 57 57-29-28Z" />
          </svg>
        </button>
        <button
          onClick={onDelete}
          className="text-gray-600 transition-colors hover:text-red-600"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            height="16"
            width="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M18 6L6 18M6 6l12 12" />
          </svg>
        </button>
      </div>
      <CardContent className="p-4">
        <h4 className="mb-2 font-medium">{title}</h4>
        <p>{content}</p>
      </CardContent>
      <CardFooter className="justify-end p-4 pt-0 text-xs text-gray-500">
        Generated by {source}
      </CardFooter>
    </Card>
  );
}
