// Per-study-type pricing constants (in cents)
export const PERSONAL_EVALUATION_COST_CENTS = 499; // $4.99
export const PERSONAL_WALKTHROUGH_COST_CENTS = 499; // $4.99
export const PERSONAL_PERSONA_COST_CENTS = 249; // $2.49
export const COMPANY_EVALUATION_COST_CENTS = 1999; // $19.99
export const COMPANY_WALKTHROUGH_COST_CENTS = 1999; // $19.99
export const COMPANY_PERSONA_COST_CENTS = 499; // $4.99
export const PERSONAL_QUAL_ANALYSIS_COST_CENTS = 1499; // $14.99
export const COMPANY_QUAL_ANALYSIS_COST_CENTS = 4499; // $44.99
export const PERSONAL_LIVE_SESSION_COST_CENTS = 499; // $4.99
export const COMPANY_LIVE_SESSION_COST_CENTS = 1999; // $19.99
export const PERSONAL_LIVE_AI_ANALYSIS_COST_CENTS = 999; // $9.99 (discounted from $14.99)
export const COMPANY_LIVE_AI_ANALYSIS_COST_CENTS = 2999; // $29.99 (discounted from $44.99)
export const PERSONAL_INTERVIEW_COST_CENTS = 499; // $4.99
export const COMPANY_INTERVIEW_COST_CENTS = 1999; // $19.99

// Backward-compatible aliases (highest per-type cost)
// Used for balance threshold warnings, minimum fund amounts, and auto-refill checks
export const PERSONAL_STUDY_COST_CENTS = PERSONAL_QUAL_ANALYSIS_COST_CENTS;
export const COMPANY_STUDY_COST_CENTS = COMPANY_QUAL_ANALYSIS_COST_CENTS;

// Lowest per-type cost — used for balance exhaustion checks
export const PERSONAL_MIN_STUDY_COST_CENTS = PERSONAL_PERSONA_COST_CENTS;
export const COMPANY_MIN_STUDY_COST_CENTS = COMPANY_PERSONA_COST_CENTS;

// General funding & balance limits
export const MAX_FUND_AMOUNT_CENTS = 500000; // Maximum funding amount in cents ($5,000.00)
export const INITIAL_BALANCE_CENTS = 1497; // Initial balance for new users (3 × $4.99 = $14.97)

// Consolidated study pricing configuration object
export const STUDY_PRICING = {
  PERSONAL: {
    EVALUATION: PERSONAL_EVALUATION_COST_CENTS,
    WALKTHROUGH: PERSONAL_WALKTHROUGH_COST_CENTS,
    PERSONA: PERSONAL_PERSONA_COST_CENTS,
    QUAL_ANALYSIS: PERSONAL_QUAL_ANALYSIS_COST_CENTS,
    LIVE_SESSION: PERSONAL_LIVE_SESSION_COST_CENTS,
    LIVE_AI_ANALYSIS: PERSONAL_LIVE_AI_ANALYSIS_COST_CENTS,
    INTERVIEW: PERSONAL_INTERVIEW_COST_CENTS,
    STUDY_COST_LIMIT: PERSONAL_STUDY_COST_CENTS,
    MIN_STUDY_COST: PERSONAL_MIN_STUDY_COST_CENTS,
  },
  COMPANY: {
    EVALUATION: COMPANY_EVALUATION_COST_CENTS,
    WALKTHROUGH: COMPANY_WALKTHROUGH_COST_CENTS,
    PERSONA: COMPANY_PERSONA_COST_CENTS,
    QUAL_ANALYSIS: COMPANY_QUAL_ANALYSIS_COST_CENTS,
    LIVE_SESSION: COMPANY_LIVE_SESSION_COST_CENTS,
    LIVE_AI_ANALYSIS: COMPANY_LIVE_AI_ANALYSIS_COST_CENTS,
    INTERVIEW: COMPANY_INTERVIEW_COST_CENTS,
    STUDY_COST_LIMIT: COMPANY_STUDY_COST_CENTS,
    MIN_STUDY_COST: COMPANY_MIN_STUDY_COST_CENTS,
  },
  LIMITS: {
    MAX_FUND_AMOUNT_CENTS,
    INITIAL_BALANCE_CENTS,
  }
} as const;
