// Next imports
import { redirect } from "next/navigation";
import Link from "next/link";

// Lib function imports
import { convertFromHeuristicType, getPresignedUrls } from "@/lib/action";
import { isAuthenticated } from "@/lib/dal";
import { getHeuristicEvaluation, updateStudyName } from "@/lib/data";

// Components imports
import MoreMenu from "@/components/study-details-more-menu";
import Title from "@/components/title";

// UI component imports
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import Gallery from "@/components/gallery";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";

// Prism imports
import { ViolatedType } from "@prisma/client";

// Type imports
import { HEResultData } from "@/types/types";

export default async function Page({ params }: { params: { id: string } }) {
  const session = await isAuthenticated();

  const study = await getHeuristicEvaluation(params.id, session.userId);

  if (!study || !study.heuristicEvaluation) {
    redirect("/error");
  }

  if (session.userId !== study.userId) {
    // TODO: Need to redirect to a better page
    redirect("/error");
  }

  // Get presigned URLs for the study files
  const presignedUrls = await Promise.all(
    study.files.map((file) => (file.key ? getPresignedUrls(file.key) : "")),
  );

  // Group the heuristic evaluation results by heuristic ID.
  const groupedResultsByHeuristic = study.heuristicEvaluation.results.reduce(
    (acc: { [key: string]: HEResultData[] }, result) => {
      if (!acc[result.heuristicId]) {
        acc[result.heuristicId] = [];
      }
      acc[result.heuristicId].push(result);
      return acc;
    },
    {},
  );

  // Generate table rows and count of violated heuristics
  const { violated, rows } = generateTableRows(groupedResultsByHeuristic);

  const TABLE_HEAD = ["Heuristic", "Violated", "Reason", "Recommendation"];

  // Function to generate table rows and count of violated heuristics
  function generateTableRows(groupedResultsByHeuristic: {
    [key: string]: HEResultData[];
  }) {
    const rows: JSX.Element[] = [];
    let violated: number = 0;

    Object.keys(groupedResultsByHeuristic || {}).forEach((key) => {
      const items = groupedResultsByHeuristic[key];
      const isViolated = items.some(
        (item) => item.violated === ViolatedType.YES,
      );

      if (isViolated) {
        violated++;

        // For violated heuristics, collect reasons
        const violatedItems = items.filter(
          (item) => item.violated === ViolatedType.YES,
        );
        rows.push(
          <TableRow key={items[0].id}>
            <TableCell className="align-top">
              {items[0].heuristic?.heuristic || "N/A"}
            </TableCell>
            <TableCell className="align-top">
              <span className="font-bold text-red-500">Yes</span>
            </TableCell>
            <TableCell className="align-top">
              {violatedItems.map((item, index) => (
                <Card
                  key={index}
                  className={
                    index === violatedItems.length - 1
                      ? "bg-indigo-100"
                      : "mb-4 bg-indigo-100"
                  }
                >
                  <CardContent className="p-2">{item.reason}</CardContent>
                  <CardFooter className="w-full justify-end p-2 pt-0 text-right text-xs text-gray-400">
                    {`Generated by ${item.source}`}
                  </CardFooter>
                </Card>
              ))}
            </TableCell>
            <TableCell className="align-top">
              {violatedItems.map((item, index) =>
                item.recommendations.map((recommendation, index) => (
                  <Card
                    key={index}
                    className={
                      index === violatedItems.length - 1
                        ? "bg-indigo-100"
                        : "mb-4 bg-indigo-100"
                    }
                  >
                    <CardContent className="p-2">
                      {recommendation.recommendation}
                    </CardContent>
                    <CardFooter className="w-full justify-end p-2 pt-0 text-right text-xs text-gray-400">
                      {`Generated by ${recommendation.source}`}
                    </CardFooter>
                  </Card>
                )),
              )}
            </TableCell>
          </TableRow>,
        );
      } else {
        // For non-violated heuristics
        const nonViolatedItem = items[0]; // Use any item since all have violated: 'NO'
        rows.push(
          <TableRow key={nonViolatedItem.id}>
            <TableCell>
              {nonViolatedItem.heuristic?.heuristic || "N/A"}
            </TableCell>
            <TableCell>No</TableCell>
            <TableCell></TableCell>
            <TableCell></TableCell>
          </TableRow>,
        );
      }
    });

    return { violated, rows };
  }

  return (
    <div>
      <Breadcrumb className="mb-6">
        <BreadcrumbList>
          <BreadcrumbItem>
            <BreadcrumbLink>
              <Link href="/studies">Studies</Link>
            </BreadcrumbLink>
          </BreadcrumbItem>
          <BreadcrumbSeparator />
          <BreadcrumbItem>
            <BreadcrumbPage>Results</BreadcrumbPage>
          </BreadcrumbItem>
        </BreadcrumbList>
      </Breadcrumb>

      <div className="mb-4 flex">
        <div className="flex flex-grow flex-col">
          <small className="text-sm font-bold uppercase leading-none text-zinc-500">
            Heuristic Evaluation
          </small>
          <Title
            studyId={study.id}
            userId={session.userId}
            updateStudyName={updateStudyName}
          >
            {study.name ? study.name : "Untitled"}
          </Title>
        </div>
        <div className="ml-4 flex">
          <MoreMenu study={study} sessionId={session.userId} />
        </div>
      </div>

      <div className="mb-4 flex">
        <div className="flex-grow">
          <p className="font-semibold leading-7 tracking-tight">User goal</p>
          <p className="leading-7">{study.heuristicEvaluation.goal}</p>
        </div>
      </div>

      <div className="mb-4 flex">
        <div className="flex-grow">
          <p className="font-semibold leading-7 tracking-tight">
            Additional context
          </p>
          <p className="leading-7">
            {study.heuristicEvaluation.context
              ? study.heuristicEvaluation.context
              : "None"}
          </p>
        </div>
      </div>

      <div className="mb-8 flex flex-nowrap items-center justify-between gap-4 overflow-x-auto">
        <Gallery presignedUrls={presignedUrls} />
      </div>

      <div className="mb-4 flex">
        <div className="flex-grow">
          <p className="font-semibold leading-7 tracking-tight">Heuristics</p>
          <p className="leading-7">
            {convertFromHeuristicType(study.heuristicEvaluation.type)}
          </p>
        </div>
        <div className="flex">
          <p className={`${violated > 0 ? "text-red-500" : ""}`}>
            <span className="text-4xl">{violated}</span>
            <span>
              {` violated ${violated === 1 ? "heuristic" : "heuristics"}
              `}
            </span>
          </p>
        </div>
      </div>

      <Card className="container mx-auto mb-6 h-full w-full">
        <Table>
          <TableHeader>
            <TableRow>
              {TABLE_HEAD.map((head, index) => (
                <TableHead key={index}>{head}</TableHead>
              ))}
            </TableRow>
          </TableHeader>
          <TableBody>{rows}</TableBody>
        </Table>
      </Card>
    </div>
  );
}
